import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    home: "Home",
    collection: "Collection",
    silverCollection: "Silver Collection",
    customize: "Customize",
    contact: "Contact",
    // Home Hero
    heroTitleLine1: "Elegance in",
    heroTitleLine2: "Every Detail",
    heroDesc: "Discover our exclusive collection of handcrafted jewelry, designed to make your special moments truly unforgettable.",
    exploreCollection: "Explore Collection",
    bookConsultation: "Book Consultation",
    // Home Features
    premiumQuality: "Premium Quality",
    qualityDesc: "Certified diamonds and highest purity gold crafted to perfection.",
    secureShopping: "Secure Shopping",
    secureDesc: "100% secure transactions with insured worldwide shipping.",
    expertCraftsmanship: "Expert Craftsmanship",
    expertDesc: "Decades of experience in creating timeless jewelry masterpieces.",
    // Home Trending
    trendingCollection: "Trending Collection",
    viewDetails: "View Details",
    viewAllJewelry: "View All Jewelry",
    // Home Bridal
    bridalCollection: "Bridal Collection 2026",
    bridalDesc: "Make your special day extraordinary with our handcrafted bridal jewelry sets. Designed to make you feel like royalty.",
    exploreBridal: "Explore Bridal",
    // Home Showcase
    ourShowcase: "Our Showcase",
    showcaseDesc: "Explore our curated selection of signature jewelry designs, displaying the pinnacle of craftsmanship and luxury.",
    slide1Title: "Royal Peacock Ring",
    slide1Subtitle: "22K Gold Handcrafted Masterpiece",
    slide2Title: "Emerald Elegance Ring",
    slide2Subtitle: "Premium Cushion Cut Emerald",
    slide3Title: "Classic Teardrop Necklace",
    slide3Subtitle: "Brilliant Cut Diamonds on Rose Gold",
    slide4Title: "Imperial Ruby Choker",
    slide4Subtitle: "Royal Gold Choker with Ruby Drops",
    slide5Title: "Artisanal Gold Hathpan",
    slide5Subtitle: "Delicate Floral Filigree Craftsmanship",
    // Home About/Legacy
    legacyTitle: "Our Legacy of 110 Years",
    legacyDesc: "Since 1916, Devkrupa Jewellers has stood as a symbol of trust, purity, and unparalleled craftsmanship. With over a century of heritage in Ahmedabad, we have been crafting not just jewelry, but generations of memories. Our 110-year journey is built on the unwavering faith of our customers and our commitment to bringing you the finest gold and diamond masterpieces.",
    // Home Speciality
    ourSpeciality: "Our Speciality",
    specialityTitle: "Handcrafted Kundan & Pearl Heritage Choker",
    specialityDesc: "This signature masterpiece showcases the pinnacle of heritage craftsmanship. Intricately designed in 22K yellow gold, it features precision-set Kundan stones bordered by rows of delicate seed pearls and hanging gold bead tassels. It is a timeless symbol of royal elegance, perfect for adding extraordinary grace to your most cherished occasions.",
    // Home Customize
    customizeCollectionSection: "Customize Collection",
    customizeSubtitle: "Bespoke Jewelry Design",
    customizeDesc: "Have a dream design in mind? Let us craft a bespoke masterpiece tailored exclusively for you. Whether you want to customize this gorgeous diamond necklace or bring an entirely new design to life, our master artisans will work closely with you to realize your vision with unmatched precision and grace.",
    // Products
    ourCollection: "Our Collection",
    collectionDesc: "Browse through our exquisite range of jewelry, carefully curated for every occasion.",
    filters: "Filters",
    categories: "Categories",
    priceRange: "Price Range",
    // Product Detail
    material: "Material",
    weight: "Weight",
    diamondCut: "Diamond Cut",
    purity: "Purity",
    inquireWhatsApp: "Inquire on WhatsApp",
    bookVideoCall: "Book Video Call",
    lifetimeWarranty: "Lifetime Warranty",
    insuredShipping: "Insured Shipping",
    easyReturns: "Easy Returns",
    productDesc: "Experience the epitome of elegance with this masterfully crafted ring. Designed to capture light from every angle.",
    // Contact
    contactUs: "Contact Us",
    contactDesc: "Have a question about a piece? Want to book a custom consultation? We're here to help.",
    getInTouch: "Get In Touch",
    ourShowroom: "Our Showroom",
    phone: "Phone",
    email: "Email",
    businessHours: "Business Hours",
    monSat: "Monday - Saturday:",
    sunday: "Sunday:",
    sendMsg: "Send us a Message",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    message: "Message",
    sendInquiry: "Send Inquiry",
    // Footer
    aboutDesc: "Crafting timeless elegance and unparalleled beauty. Discover our exquisite collection of premium jewelry designed for your most precious moments.",
    quickLinks: "Quick Links",
    contactInfo: "Contact Info",
    rightsReserved: "All rights reserved.",
    viewLocation: "View Location",
    // Categories
    catAll: "All",
    catRings: "Rings",
    catBridalCollection: "Bridal Collection",
    catDiamondNecklaces: "Diamond Necklaces",
    catEarrings: "Earrings",
    catBangles: "Bangles",
    catMangalsutra: "Mangalsutra",
    catSilverPayal: "Silver Payal",
    catSilverKamarband: "Silver Kamarband",
    catPoojaItems: "Pooja Items",
    catSilverBracelet: "Silver Bracelet",
    catSilverRings: "Silver Rings",
    royalSolitaireRing: "Royal Solitaire Ring",
    login: "Login",
    signup: "Sign Up",
    profile: "Profile",
    logout: "Logout",
    alreadyHaveAccount: "Already have an account? Login",
    dontHaveAccount: "Don't have an account? Sign Up",
    createAccount: "Create Account",
    enterDetails: "Enter your details below to access your account",
    authRequired: "Authentication Required",
    collectionsProtectedMsg: "Please sign in or create an account to view our premium collections.",
    cart: "Cart",
    addToCart: "Add to Cart",
    addedToCart: "Added!"
  },
  hi: {
    home: "होम",
    collection: "संग्रह",
    silverCollection: "चांदी संग्रह",
    customize: "कस्टमाइज़",
    contact: "संपर्क करें",
    heroTitleLine1: "हर विवरण में",
    heroTitleLine2: "सुंदरता",
    heroDesc: "हमारे हाथ से बने गहनों के विशेष संग्रह की खोज करें, जो आपके खास पलों को वास्तव में अविस्मरणीय बनाने के लिए डिज़ाइन किए गए हैं।",
    exploreCollection: "संग्रह देखें",
    bookConsultation: "परामर्श बुक करें",
    premiumQuality: "प्रीमियम गुणवत्ता",
    qualityDesc: "प्रमाणित हीरे और उच्चतम शुद्धता वाले सोने को पूर्णता से गढ़ा गया है।",
    secureShopping: "सुरक्षित खरीदारी",
    secureDesc: "बीमाकृत विश्वव्यापी शिपिंग के साथ 100% सुरक्षित लेनदेन।",
    expertCraftsmanship: "विशेषज्ञ शिल्प कौशल",
    expertDesc: "कालातीत आभूषण मास्टरपीस बनाने का दशकों का अनुभव।",
    trendingCollection: "ट्रेंडिंग संग्रह",
    viewDetails: "विवरण देखें",
    viewAllJewelry: "सभी आभूषण देखें",
    bridalCollection: "ब्राइडल संग्रह 2026",
    bridalDesc: "हमारे हाथ से बने ब्राइडल ज्वेलरी सेट के साथ अपने खास दिन को असाधारण बनाएं।",
    exploreBridal: "ब्राइडल देखें",
    // Home Showcase
    ourShowcase: "हमारा शोकेस",
    showcaseDesc: "हमारे चुनिंदा आभूषण डिजाइनों के विशेष संग्रह को देखें, जो उत्कृष्ट शिल्प कौशल और विलासिता को प्रदर्शित करता है।",
    slide1Title: "रॉयल मोर अंगूठी",
    slide1Subtitle: "22K सोने से बनी हस्तनिर्मित उत्कृष्ट कृति",
    slide2Title: "पन्ना लालित्य अंगूठी",
    slide2Subtitle: "प्रीमियम कुशन कट पन्ना",
    slide3Title: "क्लासिक टियरड्रॉप हार",
    slide3Subtitle: "रोज़ गोल्ड पर शानदार नक्काशीदार हीरे",
    slide4Title: "शाही रूबी चोकर",
    slide4Subtitle: "रूबी बूंदों के साथ शाही सोने का चोकर",
    slide5Title: "कारीगरी गोल्ड हाथपान",
    slide5Subtitle: "नाजुक पुष्प नक्काशीदार शिल्प कौशल",
    legacyTitle: "110 वर्षों की हमारी विरासत",
    legacyDesc: "1916 से, देवकृपा ज्वैलर्स विश्वास, शुद्धता और अद्वितीय शिल्प कौशल के प्रतीक के रूप में खड़ा है। अहमदाबाद में एक सदी से अधिक की विरासत के साथ, हम केवल आभूषण नहीं, बल्कि पीढ़ियों की यादें गढ़ रहे हैं। हमारी 110 वर्ष की यात्रा हमारे ग्राहकों के अटूट विश्वास और आपको बेहतरीन सोने और हीरे की उत्कृष्ट कृतियाँ लाने की हमारी प्रतिबद्धता पर बनी है।",
    // Home Speciality
    ourSpeciality: "हमारी विशेषता",
    specialityTitle: "हस्तनिर्मित कुंदन और मोती हेरिटेज चोकर",
    specialityDesc: "यह सिग्नेचर मास्टरपीस शिल्प कौशल के शिखर को दर्शाता है। 22K पीले सोने में जटिल रूप से डिज़ाइन किए गए इस चोकर में बारीक मोतियों और सोने के मोतियों की लटकन से घिरे हुए कुंदन पत्थर लगे हैं। यह शाही भव्यता का एक कालातीत प्रतीक है, जो आपके सबसे पसंदीदा अवसरों में असाधारण शोभा जोड़ता है।",
    // Home Customize
    customizeCollectionSection: "कस्टमाइज़ संग्रह",
    customizeSubtitle: "बेस्पोक आभूषण डिजाइन",
    customizeDesc: "क्या आपके मन में कोई ड्रीम डिज़ाइन है? आइए हम आपके लिए विशेष रूप से हस्तनिर्मित उत्कृष्ट कृति तैयार करें। चाहे आप इस भव्य हीरे के हार को कस्टमाइज़ करना चाहते हैं या एक नया डिज़ाइन बनाना चाहते हैं, हमारे कारीगर आपकी मदद करेंगे और आपकी पसंद के अनुसार बारीकी से इसे तैयार करेंगे।",
    ourCollection: "हमारा संग्रह",
    collectionDesc: "हमारे आभूषणों की उत्कृष्ट श्रृंखला को ब्राउज़ करें, जो हर अवसर के लिए सावधानीपूर्वक तैयार की गई है।",
    filters: "फिल्टर्स",
    categories: "श्रेणियां",
    priceRange: "मूल्य सीमा",
    material: "सामग्री",
    weight: "वजन",
    diamondCut: "डायमंड कट",
    purity: "शुद्धता",
    inquireWhatsApp: "WhatsApp पर पूछें",
    bookVideoCall: "वीडियो कॉल बुक करें",
    lifetimeWarranty: "आजीवन वारंटी",
    insuredShipping: "बीमाकृत शिपिंग",
    easyReturns: "आसान रिटर्न",
    productDesc: "इस कुशलता से तैयार की गई अंगूठी के साथ लालित्य का अनुभव करें। हर कोण से प्रकाश पकड़ने के लिए डिज़ाइन किया गया।",
    contactUs: "संपर्क करें",
    contactDesc: "क्या आपके पास कोई प्रश्न है? कस्टम परामर्श बुक करना चाहते हैं? हम यहाँ मदद के लिए हैं।",
    getInTouch: "संपर्क में रहें",
    ourShowroom: "हमारा शोरूम",
    phone: "फोन",
    email: "ईमेल",
    businessHours: "व्यापार के घंटे",
    monSat: "सोमवार - शनिवार:",
    sunday: "रविवार:",
    sendMsg: "हमें एक संदेश भेजें",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फोन नंबर",
    message: "संदेश",
    sendInquiry: "पूछताछ भेजें",
    aboutDesc: "कालातीत लालित्य और अद्वितीय सुंदरता गढ़ना। अपने सबसे कीमती पलों के लिए प्रीमियम आभूषणों का संग्रह खोजें।",
    quickLinks: "त्वरित लिंक",
    contactInfo: "संपर्क जानकारी",
    rightsReserved: "सर्वाधिकार सुरक्षित।",
    viewLocation: "लोकेशन देखें",
    catAll: "सभी",
    catRings: "अंगूठियां",
    catBridalCollection: "ब्राइडल संग्रह",
    catDiamondNecklaces: "हीरे के हार",
    catEarrings: "कान की बाली",
    catBangles: "चूड़ियाँ",
    catMangalsutra: "मंगलसूत्र",
    catSilverPayal: "चांदी की पायल",
    catSilverKamarband: "चांदी की करधनी",
    catPoojaItems: "पूजा सामग्री",
    catSilverBracelet: "चांदी का ब्रेसलेट",
    catSilverRings: "चांदी की अंगूठियां",
    royalSolitaireRing: "रॉयल सॉलिटेयर रिंग",
    login: "लॉगिन",
    signup: "साइन अप",
    profile: "प्रोफाइल",
    logout: "लॉगआउट",
    alreadyHaveAccount: "पहले से ही खाता है? लॉगिन",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    createAccount: "खाता बनाएं",
    enterDetails: "अपने खाते तक पहुँचने के लिए नीचे अपना विवरण दर्ज करें",
    authRequired: "प्रमाणीकरण आवश्यक",
    collectionsProtectedMsg: "हमारे प्रीमियम संग्रह देखने के लिए कृपया लॉगिन करें या एक नया खाता बनाएं।",
    cart: "कार्ट",
    addToCart: "कार्ट में जोड़ें",
    addedToCart: "जुड़ गया!"
  },
  gu: {
    home: "હોમ",
    collection: "કલેક્શન",
    silverCollection: "સિલ્વર કલેક્શન",
    customize: "કસ્ટમાઇઝ",
    contact: "સંપર્ક",
    heroTitleLine1: "દરેક વિગતમાં",
    heroTitleLine2: "સુંદરતા",
    heroDesc: "તમારી ખાસ પળોને અવિસ્મરણીય બનાવવા માટે ડિઝાઇન કરાયેલ અમારા હાથથી બનાવેલા ઘરેણાંનું કલેક્શન જુઓ.",
    exploreCollection: "કલેક્શન જુઓ",
    bookConsultation: "પરામર્શ બુક કરો",
    premiumQuality: "પ્રીમિયમ ક્વોલિટી",
    qualityDesc: "પ્રમાણિત હીરા અને શુદ્ધ સોનાથી બનેલ શ્રેષ્ઠ જ્વેલરી.",
    secureShopping: "સુરક્ષિત ખરીદી",
    secureDesc: "વીમાકૃત શિપિંગ સાથે 100% સુરક્ષિત ઓનલાઇન ખરીદી.",
    expertCraftsmanship: "નિષ્ણાત કારીગરી",
    expertDesc: "શ્રેષ્ઠ ઘરેણાં બનાવવાનો દાયકાઓનો અનુભવ.",
    trendingCollection: "ટ્રેન્ડિંગ કલેક્શન",
    viewDetails: "વિગતો જુઓ",
    viewAllJewelry: "બધા ઘરેણાં જુઓ",
    bridalCollection: "બ્રાઇડલ કલેક્શન 2026",
    bridalDesc: "અમારા હાથથી બનાવેલા બ્રાઇડલ સેટ સાથે તમારા ખાસ દિવસને વધુ ખાસ બનાવો. રાણી જેવો અહેસાસ મેળવો.",
    exploreBridal: "બ્રાઇડલ જુઓ",
    // Home Showcase
    ourShowcase: "અમારું શોકેસ",
    showcaseDesc: "અમારા ખાસ ઘરેણાંની સુંદર ડિઝાઇનોનું કલેક્શન જુઓ, જે ઉત્કૃષ્ટ કારીગરી અને વૈભવને દર્શાવે છે.",
    slide1Title: "રોયલ મોર વીંટી",
    slide1Subtitle: "૨૨K ગોલ્ડ હેન્ડક્રાફ્ટ કલાકૃતિ",
    slide2Title: "એમરાલ્ડ એલિગન્સ વીંટી",
    slide2Subtitle: "પ્રીમિયમ કુશન કટ પન્ના વીંટી",
    slide3Title: "ક્લાસિક ટીયરડ્રોપ હાર",
    slide3Subtitle: "રોઝ ગોલ્ડ પર સુંદર ડાયમંડ નેકલેસ",
    slide4Title: "શાહી રૂબી ચોકર",
    slide4Subtitle: "રૂબી ટીપાં સાથે શાહી સોનાનો ચોકર સેટ",
    slide5Title: "કારીગરી ગોલ્ડ હાથપાન",
    slide5Subtitle: "પ્રીમિયમ ફ્લોરલ ફિલિગ્રી હાથપાન",
    legacyTitle: "૧૧૦ વર્ષનો અમારો ગૌરવશાળી વારસો",
    legacyDesc: "૧૯૧૬ થી, દેવકૃપા જ્વેલર્સ વિશ્વાસ, શુદ્ધતા અને બેજોડ કારીગરીનું પ્રતીક બની રહ્યું છે. અમદાવાદમાં સદી કરતાં વધુ જૂના વારસા સાથે, અમે માત્ર ઘરેણાં જ નથી બનાવતા, પરંતુ પેઢીઓની યાદોને સાચવીએ છીએ. અમારી ૧૧૦ વર્ષની આ સફર અમારા ગ્રાહકોના અતૂટ વિશ્વાસ અને તમને શ્રેષ્ઠ સોના અને હીરાના આભૂષણો આપવાની અમારી પ્રતિબદ્ધતા પર બનેલી છે.",
    // Home Speciality
    ourSpeciality: "અમારી વિશેષતા",
    specialityTitle: "હેન્ડક્રાફ્ટ કુંદન અને મોતી હેરિટેજ ચોકર",
    specialityDesc: "આ અદ્ભુત કલાકૃતિ પરંપરાગત કારીગરીની સર્વોચ્ચતા દર્શાવે છે. ૨૨K પીળા સોનામાં બારીક કોતરણી સાથે બનેલા આ ચોકરમાં કુંદન નંગ જડેલા છે, જે મોતીની નાની માળાઓ અને સોનાના મણકાના લટકનથી શોભે છે. આ શાહી વૈભવનું પ્રતીક તમારા ખાસ પ્રસંગોમાં અદભુત આકર્ષણ ઉમેરે છે.",
    // Home Customize
    customizeCollectionSection: "કસ્ટમાઇઝ કલેક્શન",
    customizeSubtitle: "બેસ્પોક જ્વેલરી ડિઝાઇન",
    customizeDesc: "શું તમારી પાસે કોઈ ખાસ ડિઝાઈનનો વિચાર છે? તો આવો, અમે તમારા માટે એક અજોડ કલાકૃતિ તૈયાર કરીએ. તમે આ સુંદર ડાયમંડ નેકલેસમાં ફેરફાર કરવા માંગો છો અથવા સંપૂર્ણપણે નવી ડિઝાઈન બનાવવા માંગો છો, અમારા કુશળ કારીગરો તમારી પસંદગી મુજબ બારીક કોતરણી સાથે તેને તૈયાર કરી આપશે.",
    ourCollection: "અમારું કલેક્શન",
    collectionDesc: "દરેક પ્રસંગ માટે કાળજીપૂર્વક તૈયાર કરાયેલ અમારી જ્વેલરી બ્રાઉઝ કરો.",
    filters: "ફિલ્ટર્સ",
    categories: "કેટેગરીઝ",
    priceRange: "કિંમત મર્યાદા",
    material: "મટિરિયલ",
    weight: "વજન",
    diamondCut: "ડાયમંડ કટ",
    purity: "શુદ્ધતા",
    inquireWhatsApp: "WhatsApp પર પૂછપરછ",
    bookVideoCall: "વીડિયો કોલ બુક કરો",
    lifetimeWarranty: "આજીવન વોરંટી",
    insuredShipping: "સુરક્ષિત શિપિંગ",
    easyReturns: "સરળ રિટર્ન",
    productDesc: "આ ખૂબ જ સુંદર રીતે તૈયાર કરેલી વીંટી સાથે રોયલ અનુભવ કરો. દરેક ખૂણેથી ચમકવા માટે ડિઝાઇન કરેલી.",
    contactUs: "સંપર્ક કરો",
    contactDesc: "કોઈ પ્રશ્ન છે? અમારો સંપર્ક કરવા માંગો છો? અમે તમારી મદદ માટે તૈયાર છીએ.",
    getInTouch: "અમારો સંપર્ક કરો",
    ourShowroom: "અમારો શોરૂમ",
    phone: "ફોન",
    email: "ઇમેઇલ",
    businessHours: "ખુલવાનો સમય",
    monSat: "સોમવાર - શનિવાર:",
    sunday: "રવિવાર:",
    sendMsg: "અમને મેસેજ મોકલો",
    fullName: "પૂરું નામ",
    emailAddress: "ઇમેઇલ એડ્રેસ",
    phoneNumber: "ફોન નંબર",
    message: "મેસેજ",
    sendInquiry: "પૂછપરછ મોકલો",
    aboutDesc: "અદ્ભુત સુંદરતા અને બેજોડ ડિઝાઇન. તમારી ખાસ પળો માટે પ્રીમિયમ ઘરેણાંનું શ્રેષ્ઠ કલેક્શન.",
    quickLinks: "ઝડપી લિંક્સ",
    contactInfo: "સંપર્ક માહિતી",
    rightsReserved: "તમામ હકો સુરક્ષિત.",
    viewLocation: "લોકેશન જુઓ",
    catAll: "બધા",
    catRings: "વીંટીઓ",
    catBridalCollection: "બ્રાઇડલ કલેક્શન",
    catDiamondNecklaces: "ડાયમંડ હાર",
    catEarrings: "બુટ્ટી",
    catBangles: "બંગડીઓ",
    catMangalsutra: "મંગળસૂત્ર",
    catSilverPayal: "સિલ્વર પાયલ",
    catSilverKamarband: "સિલ્વર કંદોરો",
    catPoojaItems: "પૂજા આઇટમ્સ",
    catSilverBracelet: "સિલ્વર બ્રેસલેટ",
    catSilverRings: "સિલ્વર વીંટીઓ",
    royalSolitaireRing: "રોયલ સોલિટેર રિંગ",
    login: "લોગિન",
    signup: "સાઇન અપ",
    profile: "પ્રોફાઇલ",
    logout: "લોગઆઉટ",
    alreadyHaveAccount: "પહેલેથી જ એકાઉન્ટ છે? લોગિન",
    dontHaveAccount: "એકાઉન્ટ નથી? સાઇન અપ કરો",
    createAccount: "એકાઉન્ટ બનાવો",
    enterDetails: "તમારા એકાઉન્ટને ઍક્સેસ કરવા માટે નીચે તમારી વિગતો દાખલ કરો",
    authRequired: "ઓથેન્ટિકેશન જરૂરી છે",
    collectionsProtectedMsg: "અમારું પ્રીમિયમ કલેક્શન જોવા માટે કૃપા કરીને સાઇન ઇન કરો અથવા એક નવું એકાઉન્ટ બનાવો.",
    cart: "કાર્ટ",
    addToCart: "કાર્ટમાં ઉમેરો",
    addedToCart: "ઉમેરાઈ ગયું!"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
